### ISSUE TITLE
Calling new beginners for Django Backend Mentorship

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#24]
Hello Everyone,

I am providing out the mentorship through opensource experience to new beginners. If you would love to be part of it, please comment and have a look at our future ideas and progress. 

- Increased security (Patches on many CVE of the older version).
- Ensured support for future growth.
- Containerize project
- Refactor codebase (Linting, PEP8, Optimization).
- New Design (Frontend).
- Unit testing.
- Improve documentation for better comprehension.
- Asynchronous (Event-based architecture).

**Comment by Romansth** [comment]
🙋‍♂️

**Comment by Aju100** [comment]
Sure @Romansth. First, all you need to do is run the project.

**Comment by a-freakish** [comment]
.

**Comment by nirajandata** [comment]
thanks @Aju100 sir , i would like to fix this issue too

**Comment by Aju100** [comment]
Hello @Romansth , @nirajandata,

I am glad you will be working on these issues. Please go ahead and contribute to this project. Thanks

Regards,
Aju Tamang
