### ISSUE TITLE
Test and run the project in your local environment

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#30]
First of all, get yourself hands-on experience on Git and Github.

- Fork and clone the project
- Follow up the documentation and guideline 
- Also spend sometime on Django and cookie-cutter Django documentation [Optional]
- Run the project and share it.

Reference: [Git and Github crash course](https://csaju.com/blog/git-github-crash-course/)

**Comment by nirajandata** [comment]
ok

**Comment by nirajandata** [comment]
![Screenshot from 2021-05-18 19-42-21](https://user-images.githubusercontent.com/53692745/118667798-0785d480-b814-11eb-9dd1-6411dffcf47b.png)
while doing docker-compose -f local.yml up , i faced connection time out issue and i managed to fix it by adding some nameserver location in networkmanager configuration file and i removed env file and hardcoded the values but i faced no main module issue and @Aju100  told me that envs are managed by docker and that's how i fixed the issue. Thanks for mentoring @Aju100 sir

**Comment by Romansth** [comment]
I've successfully run the project using docker. Thank you so much @Aju100  and @nirajandata for helping me out.
![screen2](https://user-images.githubusercontent.com/53575561/118686127-73236e00-b823-11eb-8518-28e3237921e0.jpg)
