### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by Romansth** [Aju100/Django-Backend-mentorship#31]
hi @Aju100 . I am getting the following error while running python3 manage.py command. Could you please help me out?
_Traceback (most recent call last):
  File "/home/roman/Documents/Opensource/Opensource/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'_

**Comment by Aju100** [comment]
Hi @Romansth,

The great issue can you share a screenshot of it. Looks like you haven't defined environment variables.

**Comment by Romansth** [comment]
Here is the screenshot of the issue.
![image](https://user-images.githubusercontent.com/53575561/118384898-ec577100-b629-11eb-96d5-5f776e1386cb.png)

**Comment by Aju100** [comment]
Please go through their doc: [https://github.com/pydanny/cookiecutter-django](https://github.com/pydanny/cookiecutter-django)

Also, create .env and add an environment variable for DB one.
Reference: https://stackoverflow.com/questions/44693485/where-do-i-set-environment-variables-for-django

**Comment by Romansth** [comment]
I want to run the project locally offline. If I use online db, I won't be able to run the project offline right? Are there any alternatives than setting db url?

**Comment by Aju100** [comment]
Go with a docker installation process.😀

**Comment by Aju100** [comment]
@Romansth  Did the issue resolve ??

**Comment by Romansth** [comment]
I had been setting up a new wifi and installing a new OS on my laptop so didn't have much time. Will look into it by today or tomorrow.

**Comment by Aju100** [comment]
Sure @Romansth .

**Comment by Romansth** [comment]
@Aju100 I am able to run the project using docker. But only the templates from signin and login are loading. Is it a bug or do i need to sugnin to acces home.html? 
![screen](https://user-images.githubusercontent.com/53575561/118683353-09a26000-b821-11eb-8737-e5318210dcea.jpg)
![screen1](https://user-images.githubusercontent.com/53575561/118683444-20e14d80-b821-11eb-8b17-ba1f6762ac51.jpg)

**Comment by Aju100** [comment]
Awesome. Cool no it's done it's just about starting the project and testing on your machine. Update your progress https://github.com/Aju100/Django-Backend-mentorship/issues/30 this issue. thanks

**Comment by Romansth** [comment]
Great! Thanks
