### ISSUE TITLE
Main module not found error (the error is shown in docs file)

### ISSUE THREAD

**Issue by nirajandata** [Aju100/Django-Backend-mentorship#32]
![Screenshot from 2021-05-18 17-07-47](https://user-images.githubusercontent.com/53692745/118644654-c1be1180-b7fd-11eb-87d1-37c676fd94c0.png)
I just managed to delete env variable and added the values directly and when i tried to run it with docker-compose , i m having sort of error inside of docs file , can you help me

**Comment by nirajandata** [comment]
btw , i only used real value in databases_url instead of env_variable called db_ur and removed some email_backends as i didn't  had acess to the .env files so

**Comment by Aju100** [comment]
first of all, did u properly installed the requirements.txt of a local one.

**Comment by nirajandata** [comment]
yes , i already installed all the packages of local

**Comment by Aju100** [comment]
Let me test and quickly update you on this issue. Thanks

**Comment by Aju100** [comment]
Hi @nirajandata ,

I don't have a problem with the running project in a docker container. Have a look.
![update](https://user-images.githubusercontent.com/29862610/118650460-36944a00-b804-11eb-9b36-809c59538eaf.png)

Steps to run the project
- clone the project && cd project
- docker-compose -f local.yml up
- port will be exposed on localhost:8000

**Comment by nirajandata** [comment]
thanks, it worked

**Comment by Aju100** [comment]
@nirajandata  you are welcome. I will be closing this issue.
