### ISSUE TITLE
ModuleNotFoundError: No module named 'main' in sphinx server

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#33]
There is a misconfiguration for setting up the docs generator using sphinx.

Steps to reproduce
- Clone the repo
- sudo docker-compose -f local.yml up docs

> Make sure you install docker and docker-compose on your machine.

Solution:
- App named as "main" is not properly registered in the Django application's settings 
- Configure it properly

Reference:
- https://docs.djangoproject.com/en/3.2/intro/tutorial02/
- https://cookiecutter-django.readthedocs.io/en/latest/
- https://stackoverflow.com/questions/41933615/proper-way-to-register-apps-in-django
- https://docs.djangoproject.com/en/3.2/ref/applications/

**Comment by Romansth** [comment]
hi @Aju100 . I'll look after this issue.

**Comment by Aju100** [comment]
HI @Romansth , this issue has been assigned to Nirajan. You can look this issue. https://github.com/Aju100/Django-Backend-mentorship/issues/34

**Comment by Romansth** [comment]
Sure!

**Comment by nirajandata** [comment]
Hi @Aju100  , i tried to fix the error by importing it in a base.py file and tried to register it here but it shows not module named apps . When i tried to dive deep into issue , i tried to import apps.py by creating another python file and i was able to import it . Here is my code of another python file `from pathlib import Path
import sys

ROOT_DIR = Path(__file__).resolve(strict=True).parent.parent.parent
main_dir=str(ROOT_DIR)+'/main/'
sys.path.append(main_dir)
import apps
`

**Comment by Aju100** [comment]
Hi @nirajandata,

Thanks, I understand you are able to import it in the python list of Django apps. What about if I create an app and wanted to register new app?

How will you handle at this situation?

**Comment by nirajandata** [comment]
Hello @Aju100 ,the issue is that  i am not able to register the MainConfig app in apps.py as i was having issuein  importing it in base.py. Can you help me with it

**Comment by Aju100** [comment]
Hi @nirajandata I think it works well as far as you explain in the codebase. Can you sent me PR by creating out the new branch of fix issue. I will test and will give you feedback.

**Comment by Aju100** [comment]
@nirajandata , Also you will be taking this #36 with this one as both are related to each other.

**Comment by nirajandata** [comment]
thanks @Aju100  , the problem is solved

**Comment by Aju100** [comment]
Hey @nirajandata ,

Now validate whether it has been completed configure or not.

**Comment by nirajandata** [comment]
![Screenshot from 2021-05-21 15-33-29](https://user-images.githubusercontent.com/53692745/119118993-7a789080-ba4a-11eb-8069-4a89deec883e.png)
Here is the snapshot of the running code as a proof
