### ISSUE TITLE
Delete main app in the parent class directory

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#36]

**Comment by nirajandata** [comment]
Should i have to delete the directory and put the files inside it in the todo directory or should i have to move it inside todo dir?

**Comment by nirajandata** [comment]
the problem is solved

**Comment by Aju100** [comment]
> Should i have to delete the directory and put the files inside it in the todo directory or should i have to move it inside todo dir?

as your wish but I have to review out.

**Comment by nirajandata** [comment]
okay

**Comment by nirajandata** [comment]
you can check my solution at the feature branch named "nomodulelogs". here is my codebase : https://github.com/nirajandata/Django-Backend-mentorship/tree/nomodulelogs

**Comment by Aju100** [comment]
Issue fixed #40
