### ISSUE TITLE
Email verification system is not working as it should be

### ISSUE THREAD

**Issue by nirajandata** [Aju100/Django-Backend-mentorship#38]
![Screenshot from 2021-05-21 18-59-37](https://user-images.githubusercontent.com/53692745/119144667-9d19a200-ba68-11eb-84e2-cc07e3accd86.png)
Hi @Aju100 , when i tried to sign up a new account  , i was not able to get the verification code (even in the spam mail).
Can you help us us to solve the issue !

**Comment by Aju100** [comment]
Did you go through Django cookiecutter documentation for setting out the email configuration one?

**Comment by Romansth** [comment]
@nirajandata  maybe it's not working because we haven't set the host for sending mails in base.py
