### ISSUE TITLE
Customize Jazz admin

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#42]
Django comes with default admin but the UI is not good as it should be. To enhance UI/UX experience, we need to change the default one to another one.

Install jazzmin django admin apps and configure in base.py of config modules.

Reference : https://github.com/farridav/django-jazzmin

**Comment by nirajandata** [comment]
okay @Aju100

**Comment by nirajandata** [comment]
can you check the pr @Aju100
