### ISSUE TITLE
Install and configure fake admin panel

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#43]
Any attackers can easily grab out the admin panel URL and try to brute force to access the credentials. One way to bypass is to perform a rate limit or blacklisted the IP. We will do this in the upcoming future. Right now, we can still try out best by creating a fake admin panel so that attackers perform brute force into the wrong admin panel so they can be easily tricked.

Install the honeypot package and configure in the settings.

Reference:
- https://github.com/dmpayton/django-admin-honeypot/

**Comment by Romansth** [comment]
Hi @Aju100  I'd like to work on this issue.

**Comment by Romansth** [comment]
hi @Aju100 . I was setting up django-admin-honeypot for fake admin panel. I first pip installed honeypot and then added it in project settings.py installed apps as well as created a url route for the page. While running the project, the fake admin page gets loaded and works as well but I'm getting this error on my console though the honeypot library is actually working.
![image](https://user-images.githubusercontent.com/53575561/119780666-d4190900-bee9-11eb-85b4-cbf880489916.png)

**Comment by Aju100** [comment]
@Romansth Did you add the honeypot in requirements.txt and restart the docker container?

**Comment by Romansth** [comment]
@Aju100  I've sent a pr for this issue please review it.
