### ISSUE TITLE
Add issue and pull request template

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#51]

**Comment by Romansth** [comment]
Hi @Aju100 . I'd like to work on this issue.

**Comment by Aju100** [comment]
sure you can work on it.

**Comment by Romansth** [comment]
@Aju100 do i need to include flake8 and tox tests in the contrbuting guidelines?

**Comment by Aju100** [comment]
@Romansth Yes you have to include it too.

**Comment by Romansth** [comment]
HI @Aju100. I've created a new file called CONTRIBUTING.rst which contains general guidelines for contributing to this project. I've send the pr for this. The CONTRIBUTING.rst has run successfully on my local machine.
![image](https://user-images.githubusercontent.com/53575561/120761507-fbe51e00-c534-11eb-9302-06ca822aac00.png)

**Comment by Romansth** [comment]
@Aju100  can you give me any reference links for the template?
