### ISSUE TITLE
[Add] test for Django tasks model

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#54]
Evaluation of the Django project against requirements gathered from users and system specifications is required. This might solve huge time instead of performing manual tests.
 
Reference:
- https://docs.djangoproject.com/en/3.2/topics/testing/overview/
- https://realpython.com/testing-in-django-part-1-best-practices-and-examples/
- https://www.digitalocean.com/community/tutorials/how-to-add-unit-testing-to-your-django-project

**Comment by Romansth** [comment]
hi @Aju100. There already exists few tests inside todo-->users for django. I'm not so sure which tests I am supposed to write and for which models present in which directory since there already exists tests in the main todo app. Could you possibly give me some hints?

**Comment by Aju100** [comment]
@Romansth you are required to write a test for the recently registered app(task model).

**Comment by Romansth** [comment]
Hi @Aju100 . I'm a bit confused about writing the tests. Is this the way of writing tests or should I create a dummy class with dummy data for the tests. 
![image](https://user-images.githubusercontent.com/53575561/121455025-87423180-c9c3-11eb-8afa-d40573a0f82d.png)

**Comment by Romansth** [comment]
Also, I'm getting this error while running pytest command.
![image](https://user-images.githubusercontent.com/53575561/121455218-ce302700-c9c3-11eb-9f73-b24d7290e600.png)

**Comment by Aju100** [comment]
Yes but I am preferring you go to with unittest.
