### ISSUE TITLE
[Remove] the hard coded internal IP in base.py

### ISSUE THREAD

**Issue by Aju100** [Aju100/Django-Backend-mentorship#57]
location: config/settings/local.py

Remove the below-harded code
```
INTERNAL_IPS = ["127.0.0.1", "10.0.2.2"]
```

Reference:
- https://pypi.org/project/python-decouple/
- https://simpleisbetterthancomplex.com/2015/11/26/package-of-the-week-python-decouple.html

**Comment by nirajandata** [comment]
@Aju100  , ok i will look into this

**Comment by Aju100** [comment]
sure @nirajandata . you will be rocking

**Comment by nirajandata** [comment]
can you check the pr @Aju100

**Comment by Aju100** [comment]
@nirajandata  thanks for the PR
