### ISSUE TITLE
[Bug] ConnectionError at /adminlogin/

### ISSUE THREAD

**Issue by nirajandata** [Aju100/Django-Backend-mentorship#64]
i am having this issue while going to admin url through /admin url
![Screenshot from 2021-06-14 16-31-03](https://user-images.githubusercontent.com/53692745/121881317-d6bf8f00-cd2e-11eb-96d2-14ffba15de07.png)

**Comment by Aju100** [comment]
it will be better if you share out the steps to reproduce the error. Also did u test on your local machine ?

**Comment by nirajandata** [comment]
i reinstalled the codespace and it started working magically .

**Comment by Aju100** [comment]
awesome @nirajandata

**Comment by nirajandata** [comment]
@Aju100 , i figured out this error occured due to installation of django-defender , can you try it in your environment

**Comment by Aju100** [comment]
show me the error and ss

**Comment by nirajandata** [comment]
@Aju100  it is the same error

**Comment by Aju100** [comment]
@nirajandata  All you need to clean out the docker cache images and refresh the installation.

**Comment by Aju100** [comment]
@nirajandata  Is this issue still going or not? Otherwise, we can disclose this issue.

**Comment by nirajandata** [comment]
i still don't know how to fix it

**Comment by nirajandata** [comment]
this only occured while while defender
