### ISSUE TITLE
ERROR: improperlyconfigured

### ISSUE THREAD

**Issue by nirajandata** [Aju100/Django-Backend-mentorship#69]
I tried testing the django model and open the django shell in the docker and when i try to import the model , i am facing some environmental variable issue 
![image](https://user-images.githubusercontent.com/53692745/123962943-b3a10a80-d9d1-11eb-9ad2-12af1fe5c0cb.png)

**Comment by Aju100** [comment]
@nirajandata Any steps to reproduce the issue

**Comment by nirajandata** [comment]
docker-compose -f local.yml run django django-admin shell

**Comment by Aju100** [comment]
can you work without using shell right now, we can look further this issue

**Comment by nirajandata** [comment]
sure
